pcan-lemonaid-objs := pcan_main.o
pcan-lemonaid-objs += pcan_fops.o
pcan-lemonaid-objs += pcan_fifo.o
pcan-lemonaid-objs += pcan_filter.o
pcan-lemonaid-objs += pcan_parse.o
pcan-lemonaid-objs += pcan_sja1000.o
pcan-lemonaid-objs += pcan_common.o
pcan-lemonaid-objs += pcan_usb_core.o
pcan-lemonaid-objs += pcan_usb.o
pcan-lemonaid-objs += pcan_usbpro.o
pcan-lemonaid-objs += pcan_timing.o

obj-$(CONFIG_PCAN_LEMONAID) += pcan-lemonaid.o

